// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "ChattyGPT",
    platforms: [
        .iOS("15.2")
    ],
    products: [
        .iOSApplication(
            name: "ChattyGPT",
            targets: ["AppModule"],
            bundleIdentifier: "com.chattygpt.chattygpt",
            teamIdentifier: "3XJA79VE76",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .smiley),
            accentColor: .presetColor(.cyan),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .productivity
        )
    ],
    dependencies: [
        .package(url: "https://github.com/MacPaw/OpenAI.git", "0.0.9"..<"1.0.0"),
        .package(url: "https://github.com/siteline/SwiftUI-Introspect.git", "0.2.3"..<"1.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "OpenAI", package: "OpenAI"),
                .product(name: "Introspect", package: "SwiftUI-Introspect")
            ],
            path: "."
        )
    ]
)
